### PR TITLE
refine spelling and add shareholder summary

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
@xeroc @ryanRfox 

please have a look

### CODE REVIEW

**Comment by ryanRfox** [comment]
Yes, all of the changes look good to me. Appreciate the addition of the Shareholder Summary. I'll seek out the Everbloom guys this morning for for their review as well (not sure who to @mention).

**Comment by andrew311** [comment]
Andrew here from Everbloom. We will review with @ryanRfox.

**Comment by sschiessl-bcp** [comment]
@ryanRfox @andrew311 

I got notified that you have a google document in parallel. Please be careful with inconsistencies, rather use this PR for iteration!

**Comment by sschiessl-bcp** [comment]
Please create a new PR for new changes. Introduced drafts section now on homepage

**Pull request merged**
